# Check that fence INDEX of a chapter, counted among the fences of its
# language group, appears verbatim in SOURCE. The first line of the fence
# must match LABEL, so that a fence that moved reports itself. Run with
# cmake -P and these values:
#   CHAPTER  the index.md of the chapter
#   GROUP    code for a C or CMake fence, anti for an Anti one
#   INDEX    the number of the fence in its group, from 1
#   SOURCE   the repository file that holds the code
#   LABEL    the letters, digits, _ and spaces of the first line, at most 40

file(READ "${CHAPTER}" text)
set(rest "${text}")
set(count 0)
set(body "")
while(TRUE)
    string(FIND "${rest}" "\n```" at)
    if(at EQUAL -1)
        break()
    endif()
    math(EXPR start "${at} + 4")
    string(SUBSTRING "${rest}" ${start} -1 rest)
    string(FIND "${rest}" "\n" eol)
    string(SUBSTRING "${rest}" 0 ${eol} lang)
    math(EXPR open "${eol} + 1")
    string(SUBSTRING "${rest}" ${open} -1 rest)
    string(FIND "${rest}" "```\n" close)
    if(close EQUAL -1)
        break()
    endif()
    string(SUBSTRING "${rest}" 0 ${close} fence)
    math(EXPR after "${close} + 3")
    string(SUBSTRING "${rest}" ${after} -1 rest)
    set(in_group FALSE)
    if(GROUP STREQUAL "anti")
        if(lang STREQUAL "anti")
            set(in_group TRUE)
        endif()
    elseif(lang STREQUAL "c" OR lang STREQUAL "cmake")
        set(in_group TRUE)
    endif()
    if(in_group)
        math(EXPR count "${count} + 1")
        if(count EQUAL INDEX)
            set(body "${fence}")
            break()
        endif()
    endif()
endwhile()
if(body STREQUAL "")
    message(FATAL_ERROR "${CHAPTER} has no ${GROUP} fence ${INDEX}")
endif()
string(FIND "${body}" "\n" eol)
string(SUBSTRING "${body}" 0 ${eol} first)
string(REGEX REPLACE "[^A-Za-z0-9_ ]" "" first "${first}")
string(STRIP "${first}" first)
string(LENGTH "${LABEL}" label_length)
string(SUBSTRING "${first}" 0 ${label_length} first)
if(NOT first STREQUAL LABEL)
    message(FATAL_ERROR "fence ${INDEX} of ${CHAPTER} starts with '${first}', expected '${LABEL}'")
endif()
file(READ "${SOURCE}" source)
string(FIND "${source}" "${body}" found)
if(found EQUAL -1)
    message(FATAL_ERROR "fence ${INDEX} of ${CHAPTER} is not in ${SOURCE}\n${body}")
endif()
